# Generated by Django 4.2.11 on 2024-04-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqiwqi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MQ7Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mq7_data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PhSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PMSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_1_0', models.FloatField()),
                ('pm_2_5', models.FloatField()),
                ('pm_10_0', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TDSSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TempSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
            ],
        ),
    ]
