# Generated by Django 4.2.11 on 2024-04-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqiwqi', '0002_gpsdata_mq7data_phsensor_pmsdata_tdssensor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
